name: Latest blog post workflow
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in tistory posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://bezzang2.tistory.com/rss"
          max_post_count: 5
          user_agent: "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
          accept_header: "text/xml"
